### ISSUE TITLE
When turning on preload the css loading tag isn't included in the page.

### ISSUE THREAD

**Issue by jripmeester** [a-digital/cookie-consent-banner#26] opened 2020-08-13 20:51 UTC
Hi!

When we turn on the option to preload the css the link tag with preload attribute is loaded. But the actual link tag for loading the css isn't included in the head. Which causes the styling to fail.

I think we missing something but i can't seem to find what...

**Comment by mark-adigital** [comment] 2020-08-28 15:39
Hi,

If I'm following you correctly, I think the problem is that you need to generate the Critical CSS for the webpage yourself (which in my experience would include the banner) separately - all the setting in the plugin set the preload attribute on the CSS tag as you've seen.

Hope that helps,

Mark

**Comment by mark-adigital** [comment] 2020-09-28 10:55
Closing due lack of further feedback.

**Closed by mark-adigital** 2020-09-28 10:55 UTC
